#!/usr/bin/env bash
set -e

GH_USER=$1
GH_PAGES=${2:-3}

if [[ -z "$GH_USER" ]]; then
  if ! GH_USER=$(gh api user --template="{{- print .login -}}"); then
    echo "${GH_USER}"
    exit 1
  fi
fi

# shellcheck disable=SC2016
TEMPLATE='
  {{- range $event := . -}}
    {{- printf "%s [%s] %s\n" $event.created_at $event.type $event.repo.name -}}
  {{- end -}}
'

for a in $(eval echo "{1..$GH_PAGES}")
do
  gh api -H 'accept: application/vnd.github.v3+json' "users/$GH_USER/events?per_page=100&page=$a" --template="${TEMPLATE}"
done
